### PR TITLE
Rebuild 14.0.6 using libxml2 2.13

### PR DESCRIPTION
**Pull request by cbouss**
Rebuild for libxml2 and svml patch
- update pins
- fix overlinking errors (which were silenced on the previous build)
- refactor install scripts in line with changes from https://github.com/AnacondaRecipes/llvmdev-feedstock/pull/14 - reason: newer conda build complained about moved files.
- added patch _ Fixes vectorizer and extends SVML support_ requested by numba

Note: windows builds but fails at the signing stage.

### CODE REVIEW

**Review by skupr-anaconda — APPROVED** [review]
LGTM

**Review by danpetry — APPROVED** [review]
Any idea whether the patch should be applied to v17..?

**Comment by cbouss** [comment]
> Any idea whether the patch should be applied to v17..?

No idea, the best is to check with numba

**Comment by danpetry** [comment]
> > Any idea whether the patch should be applied to v17..?
> 
> No idea, the best is to check with numba

They said they haven't ported it yet. I asked them to reach out when they have.

**Pull request merged**
