### PR TITLE
Fix improper handling of arrays of structs on aarch64

### PR DESCRIPTION
**Pull request by AndrewVallette**
## Changes

Added `llvm-consecutive-registers` patches

## Notes

This addresses an issue where LLVM could incorrectly handle arrays of structs on `aarch64`, which results in a segfault. The first patch (`llvm-consecutive-registers.patch`) fixes the issue, but breaks the ABI. The second patch (`llvm-consecutive-registers-abi.patch`) resolves the ABI issue.

### CODE REVIEW

**Review by ScottBailey — APPROVED** [review]
The patch section could be cleaned up to remove the long ago comment out patches and any deprecated patches could be removed form the repository.

Otherwise LGTM.

**Comment by AndrewVallette** [comment]
> The patch section could be cleaned up to remove the long ago comment out patches and any deprecated patches could be removed form the repository.
> 
> Otherwise LGTM.

Thanks, I can remove those.

**Review by varlackc — COMMENTED** [review]
We might want to use the `skip section` in order specify the `python pinnings`.

https://github.com/AnacondaRecipes/llvmdev-feedstock/blob/1f28c13fd572b5f8c9c8ab024b972153808da9da/recipe/meta.yaml#L50

https://github.com/AnacondaRecipes/llvmdev-feedstock/blob/1f28c13fd572b5f8c9c8ab024b972153808da9da/recipe/meta.yaml#L83

https://github.com/AnacondaRecipes/llvmdev-feedstock/blob/1f28c13fd572b5f8c9c8ab024b972153808da9da/recipe/meta.yaml#L122

https://github.com/AnacondaRecipes/llvmdev-feedstock/blob/1f28c13fd572b5f8c9c8ab024b972153808da9da/recipe/meta.yaml#L169

**Comment by ScottBailey** [comment]
> We might want to use the `skip section` in order specify the `python pinnings`.

Or remove them entirely as we no longer support python 2.

**Pull request merged**
